name: Final-Win-Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install --upgrade pip buildozer Cython==0.29.33
      - name: Build Android APK
        env:
          BUILDOZER_WARN_ON_ROOT: 1
        run: |
          # Sabse pehle saaf start karein
          buildozer android clean
          # Ab build shuru karein
          yes | buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: NetworkMaster-Final-APK
          path: bin/*.apk
