name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            zip unzip autoconf automake libtool pkg-config libncurses5-dev \
            libncursesw5-dev cmake libffi-dev libssl-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: Build Android APK
        run: |
          # 'yes' कमांड अपने आप सारे लाइसेंस स्वीकार कर लेगी
          sh -c "yes | buildozer --allow-root android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NetworkMasterPro-APK
          path: bin/*.apk
