name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            zip unzip autoconf automake libtool pkg-config libncurses5-dev \
            libncursesw5-dev cmake libffi-dev libssl-dev ant

      - name: Build APK
        run: |
          pip install "buildozer>=1.5.0" "cython<3.0.0"
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          # --verbose सबसे जरूरी है, यह हमें असली एरर बताएगा
          buildozer -v android debug
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx4096m'"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NetworkMasterPro-APK
          path: bin/*.apk
