      - name: Build with Buildozer
        run: |
          # Sab kuch saaf karke naya build [cite: 2026-01-14]
          buildozer --verbose android clean
          yes | buildozer android debug || true
          buildozer android debug
